### ISSUE TITLE
xnet

### ISSUE THREAD

**Issue by joaoespanhol** [Terrails/XNetGasses#11]
is no runner laster version mekanism

**Comment by Terrails** [comment]
Works fine on my end

**Comment by joaoespanhol** [comment]
> Works fine on my end

Mekanism-1.16.5-10.1.0.455.jar

try

**Comment by joaoespanhol** [comment]
try to use with this mod more xnet gases
@Terrails

**Comment by Terrails** [comment]
I already tried it. "Not running" doesn't help, I need the log

**Comment by joaoespanhol** [comment]
if you tested it, it has the log :)

**Comment by Terrails** [comment]
Yes, it does and according to that log there's nothing wrong. If you want me to see what's causing your "not running" issue, I need your log. You can find it in "[Game/Modpack Folder]/logs/latest.log".

**Comment by AbsolemJackdaw** [comment]
> if you tested it, it has the log :)

if a dev tests an issue out, and doesnt encounter an issue, there will be no issue logged in the afformentioned log. 
Developpers need yours, because it contains the error stack tracing of what went wrong on your end, on your computer, with your game. 
Your sassy reply doesnt help anyone. If a dev asks for a log (and mostly certainly after confirming he tried it himself and didnt encounter the same issue), you give it to him, or else he can't do anything, and you'll be stuck with a game that doesnt run as long as you use either this mod, or a mod incompatible with this mod, or whatever the issue may be

**Comment by Pustolaika** [comment]
Yes, it doesn't work for me too: Mekanism-1.16.5-10.1.0.455 and XNetGases-1.16.5-2.3.8. And yes, there is nothing wrong in log.

**Comment by Terrails** [comment]
Just to humor this again, since I tested it in dev last time, I made a fresh 1.16.5 instance with the mod installed. The game launches fine and after making a simple 2 tank setup, gases transfer fine. Can't do anything if there's nothing wrong with the log. I have tested this with latest dependencies and tried both Mekanism-1.16.5-10.1.0.455 and 456

**Comment by Pustolaika** [comment]
I've tried to create a new game and make two simple tank setup - it works!
But it doesn't work with an existing game.

**Comment by Terrails** [comment]
That's some weird behavior. Did you try to break the tanks/machines and place them again? Might be some weird issue going on with the block entity. If that doesn't work I would do the same with xnet controllers and connectors, but keep in mind that breaking the controller resets(?) the configuration.

**Comment by Pustolaika** [comment]
I play on my own server, and I tried to break the tanks and place them again. I even changed gamemode to creative and create a new network, but noting changed. Everything is ok except gases don't input and export.
![2022-01-02_06 28 44](https://user-images.githubusercontent.com/84293543/147865306-b8eef4e7-1f36-497c-bc73-9ab90e476879.png)
![2022-01-02_06 29 05](https://user-images.githubusercontent.com/84293543/147865307-7ed44ae5-1225-411f-b196-06671d7ca031.png)

**Comment by Terrails** [comment]
Found the issue, mekanism changed their equals method, so it was checking if the filter has the same amount of gas instead of just the type. This is why our simple tests in a new world probably worked, since we didn't use a filter. Would've probably never noticed this if you didn't send the screenshots. Gonna have a fix up and running asap.
