### ISSUE TITLE
Creating a gas chanel crashed the game

### ISSUE THREAD

**Issue by SorryIdrinkCoffee** [Terrails/XNetGasses#3]
I'm now here at GitHub, so I don't know whice parts of the crash report i should attach here. Here's the whole thing:
[crash-2020-12-06_16.32.37-server.txt](https://github.com/Terrails/XNetGases/files/5648919/crash-2020-12-06_16.32.37-server.txt)

Gas tank did not show up in the xnet controller and crating a gas chanel craashed the game.
I used version: XNetGases-1.16.4-2.1.0. as can be seen in the crash report.
I'm not sure if it's the xnet  or xnet gases that caused the crash.

**Comment by Terrails** [comment]
Looks like XNet got an update and something has changed in the API. I'll update it in a few mins.

**Comment by ghost** [comment]
The 1.15 version of XNet also received an update to its API. Will you also be updating the 1.15 version of this mod?

**Comment by Terrails** [comment]
Ah, will do. Gonna port the slurry channel while I'm at it.

**Comment by ghost** [comment]
Awesome, thanks so much it is appreciated!

**Comment by Terrails** [comment]
Alright, should be up on CurseForge now. Slurries already worked but it is not possible to extract them directly from the chemical dissolution chamber. Which is most likely a fault in mekanism itself. Just extract from adjacent gas tanks instead of directly from the machine for now. 

EDIT: Someone already reported the issue here [https://github.com/mekanism/Mekanism/issues/6764](https://github.com/mekanism/Mekanism/issues/6764)
