### ISSUE TITLE
mekanism.logic has no output

### ISSUE THREAD

**Issue by Tris-Barlok** [Terrails/XNetGasses#8]
"mekanism.logic" has no output, only sensors. Unfortunately, you cannot use it to implement redstone circuits without output.

I got this issues in Version:

- Minecraft  1.16.5 (Modpack Skyopolis 4 (9.0))
- Forge 36.0.46
- XNetGases-1.16.5-2.2.6
- xnet-1.16-3.0.11

**Comment by Terrails** [comment]
I see no need for this option as "xnet.logic" does the same thing. Wouldn't it just be possible to use "mekanism.logic" to get the amount of gas and output the color to "xnet.logic" for redstone output?

EDIT: Oh but I guess you would need an extra channel for this instead of using only one. I guess I'll add it back.

**Comment by Terrails** [comment]
Fixed
